// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TgCheckerApi.Models.BaseModels;

#nullable disable

namespace TgCheckerApi.Migrations
{
    [DbContext(typeof(TgDbContext))]
    [Migration("20231231170238_BebraUpdate")]
    partial class BebraUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.5.23280.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.HasKey("Id")
                        .HasName("Admin_pkey");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Apikey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("APIkeys_pkey");

                    b.ToTable("APIkeys", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("bytea")
                        .HasColumnName("avatar");

                    b.Property<int?>("Bumps")
                        .HasColumnType("integer")
                        .HasColumnName("bumps");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Flag")
                        .HasColumnType("text")
                        .HasColumnName("flag");

                    b.Property<bool?>("Hidden")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<DateTime?>("LastBump")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_bump");

                    b.Property<int?>("Members")
                        .HasColumnType("integer")
                        .HasColumnName("members");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool?>("NotificationSent")
                        .HasColumnType("boolean")
                        .HasColumnName("notification_sent");

                    b.Property<bool?>("Notifications")
                        .HasColumnType("boolean")
                        .HasColumnName("notifications");

                    b.Property<bool?>("PromoPost")
                        .HasColumnType("boolean")
                        .HasColumnName("promo_post");

                    b.Property<int?>("PromoPostInterval")
                        .HasColumnType("integer")
                        .HasColumnName("promo_post_interval");

                    b.Property<DateTime?>("PromoPostLast")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("promo_post_last");

                    b.Property<bool?>("PromoPostSent")
                        .HasColumnType("boolean")
                        .HasColumnName("promo_post_sent");

                    b.Property<TimeOnly?>("PromoPostTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("promo_post_time");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<int?>("User")
                        .HasColumnType("integer")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("Channel_pkey");

                    b.HasIndex("User");

                    b.ToTable("Channel", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.ChannelAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("channel_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("ChannelAccess_pkey");

                    b.HasIndex(new[] { "ChannelId" }, "IX_ChannelAccess_channel_id");

                    b.HasIndex(new[] { "UserId" }, "IX_ChannelAccess_user_id");

                    b.ToTable("ChannelAccess", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.ChannelHasSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("channel_id");

                    b.Property<DateTime?>("Expires")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("ChannelHasSubscription_pkey");

                    b.HasIndex(new[] { "ChannelId" }, "IX_ChannelHasSubscription_channel_id");

                    b.HasIndex(new[] { "TypeId" }, "IX_ChannelHasSubscription_type_id");

                    b.ToTable("ChannelHasSubscription", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.ChannelHasTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<int?>("Tag")
                        .HasColumnType("integer")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("ChannelHasTag_pkey");

                    b.HasIndex(new[] { "Channel" }, "IX_ChannelHasTag_channel");

                    b.HasIndex(new[] { "Tag" }, "IX_ChannelHasTag_tag");

                    b.ToTable("ChannelHasTag", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("channel_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("Comment_pkey");

                    b.HasIndex(new[] { "ChannelId" }, "IX_Comment_channel_id");

                    b.HasIndex(new[] { "ParentId" }, "IX_Comment_parent_id");

                    b.HasIndex(new[] { "UserId" }, "IX_Comment_user_id");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("channel_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("Notification_pkey");

                    b.HasIndex("ChannelId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.NotificationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Bump")
                        .HasColumnType("boolean");

                    b.Property<bool>("Important")
                        .HasColumnType("boolean");

                    b.HasKey("Id")
                        .HasName("NotificationSettings_pkey");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("NotificationType_pkey");

                    b.ToTable("NotificationType", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRenewal")
                        .HasColumnType("boolean")
                        .HasColumnName("autoRenewal");

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("channelId");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_name");

                    b.Property<int>("Discount")
                        .HasColumnType("integer")
                        .HasColumnName("discount");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<DateTime?>("Expires")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_type_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("payments_pkey");

                    b.HasIndex("ChannelId");

                    b.HasIndex("SubscriptionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("channel_id");

                    b.Property<int?>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<bool?>("NotificationSent")
                        .HasColumnType("boolean")
                        .HasColumnName("notification_sent");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("ReportTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("report_time");

                    b.Property<int?>("ReportType")
                        .HasColumnType("integer")
                        .HasColumnName("report_type");

                    b.Property<int?>("StaffId")
                        .HasColumnType("integer")
                        .HasColumnName("staff_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("Report_pkey");

                    b.HasIndex("CommentId");

                    b.HasIndex("ReportType");

                    b.HasIndex(new[] { "ChannelId" }, "IX_Report_channel_id");

                    b.HasIndex(new[] { "StaffId" }, "IX_Report_staff_id");

                    b.HasIndex(new[] { "UserId" }, "IX_Report_user_id");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.ReportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("ReportType_pkey");

                    b.ToTable("ReportType", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("Staff_pkey");

                    b.HasIndex(new[] { "UserId" }, "IX_Staff_user_id");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.StatisticsSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("channel_id");

                    b.HasKey("Id")
                        .HasName("StatisticsSheet_pkey");

                    b.HasIndex("ChannelId");

                    b.ToTable("StatisticsSheet", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.SubType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Multiplier")
                        .HasColumnType("numeric")
                        .HasColumnName("multiplier");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<int>("TagLimit")
                        .HasColumnType("integer")
                        .HasColumnName("tag_limit");

                    b.HasKey("Id")
                        .HasName("SubType_pkey");

                    b.ToTable("SubType", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.SubscribersRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("Sheet")
                        .HasColumnType("integer")
                        .HasColumnName("sheet");

                    b.Property<int>("Subscribers")
                        .HasColumnType("integer")
                        .HasColumnName("subscribers");

                    b.HasKey("Id")
                        .HasName("SubscribersRecord_pkey");

                    b.HasIndex("Sheet");

                    b.ToTable("SubscribersRecord", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("Tag_pkey");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("bytea")
                        .HasColumnName("avatar");

                    b.Property<long?>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<int?>("NotificationSettings")
                        .HasColumnType("integer")
                        .HasColumnName("notification_settings");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("UniqueKey")
                        .HasColumnType("text")
                        .HasColumnName("unique_key");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("user_pkey");

                    b.HasIndex("NotificationSettings");

                    b.HasIndex(new[] { "ChatId" }, "chat_id_uq")
                        .IsUnique();

                    b.HasIndex(new[] { "TelegramId" }, "telegram_id_uq")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.ViewsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<long?>("LastMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_message_id");

                    b.Property<int>("Sheet")
                        .HasColumnType("integer")
                        .HasColumnName("sheet");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.Property<int>("Views")
                        .HasColumnType("integer")
                        .HasColumnName("views");

                    b.HasKey("Id")
                        .HasName("ViewsRecord_pkey");

                    b.HasIndex("Sheet");

                    b.ToTable("ViewsRecord", (string)null);
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Channel", b =>
                {
                    b.HasOne("TgCheckerApi.Models.BaseModels.User", "UserNavigation")
                        .WithMany("Channels")
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_user_id");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.ChannelAccess", b =>
                {
                    b.HasOne("TgCheckerApi.Models.BaseModels.Channel", "Channel")
                        .WithMany("ChannelAccesses")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_channelaccess_channel");

                    b.HasOne("TgCheckerApi.Models.BaseModels.User", "User")
                        .WithMany("ChannelAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("user_fk");

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.ChannelHasSubscription", b =>
                {
                    b.HasOne("TgCheckerApi.Models.BaseModels.Channel", "Channel")
                        .WithMany("ChannelHasSubscriptions")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_channelhassubscription_channel");

                    b.HasOne("TgCheckerApi.Models.BaseModels.SubType", "Type")
                        .WithMany("ChannelHasSubscriptions")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("fk_Sub_type");

                    b.Navigation("Channel");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.ChannelHasTag", b =>
                {
                    b.HasOne("TgCheckerApi.Models.BaseModels.Channel", "ChannelNavigation")
                        .WithMany("ChannelHasTags")
                        .HasForeignKey("Channel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_channelhastag_channel");

                    b.HasOne("TgCheckerApi.Models.BaseModels.Tag", "TagNavigation")
                        .WithMany("ChannelHasTags")
                        .HasForeignKey("Tag")
                        .HasConstraintName("fk_ChannelHasTag_Tag");

                    b.Navigation("ChannelNavigation");

                    b.Navigation("TagNavigation");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Comment", b =>
                {
                    b.HasOne("TgCheckerApi.Models.BaseModels.Channel", "Channel")
                        .WithMany("Comments")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_channel");

                    b.HasOne("TgCheckerApi.Models.BaseModels.Comment", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("parent_id_fk");

                    b.HasOne("TgCheckerApi.Models.BaseModels.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_id_fk");

                    b.Navigation("Channel");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Notification", b =>
                {
                    b.HasOne("TgCheckerApi.Models.BaseModels.Channel", "Channel")
                        .WithMany("NotificationsNavigation")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("channel_id_fk");

                    b.HasOne("TgCheckerApi.Models.BaseModels.NotificationType", "Type")
                        .WithMany("Notifications")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("type_id_fk");

                    b.HasOne("TgCheckerApi.Models.BaseModels.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_id_fk");

                    b.Navigation("Channel");

                    b.Navigation("Type");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Payment", b =>
                {
                    b.HasOne("TgCheckerApi.Models.BaseModels.Channel", "Channel")
                        .WithMany("Payments")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("channel_id_fk");

                    b.HasOne("TgCheckerApi.Models.BaseModels.SubType", "SubscriptionType")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionTypeId")
                        .IsRequired()
                        .HasConstraintName("subtype_fk");

                    b.HasOne("TgCheckerApi.Models.BaseModels.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_id_fk");

                    b.Navigation("Channel");

                    b.Navigation("SubscriptionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Report", b =>
                {
                    b.HasOne("TgCheckerApi.Models.BaseModels.Channel", "Channel")
                        .WithMany("Reports")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("channel_id_fk");

                    b.HasOne("TgCheckerApi.Models.BaseModels.Comment", "Comment")
                        .WithMany("Reports")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("comment_id_fk");

                    b.HasOne("TgCheckerApi.Models.BaseModels.ReportType", "ReportTypeNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("ReportType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("report_type_fk");

                    b.HasOne("TgCheckerApi.Models.BaseModels.Staff", "Staff")
                        .WithMany("Reports")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("staff_id_fk");

                    b.HasOne("TgCheckerApi.Models.BaseModels.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_id_fk");

                    b.Navigation("Channel");

                    b.Navigation("Comment");

                    b.Navigation("ReportTypeNavigation");

                    b.Navigation("Staff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Staff", b =>
                {
                    b.HasOne("TgCheckerApi.Models.BaseModels.User", "User")
                        .WithMany("Staff")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_id_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.StatisticsSheet", b =>
                {
                    b.HasOne("TgCheckerApi.Models.BaseModels.Channel", "Channel")
                        .WithMany("StatisticsSheets")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("channel_id_fk");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.SubscribersRecord", b =>
                {
                    b.HasOne("TgCheckerApi.Models.BaseModels.StatisticsSheet", "SheetNavigation")
                        .WithMany("SubscribersRecords")
                        .HasForeignKey("Sheet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sub_sheet_fk");

                    b.Navigation("SheetNavigation");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.User", b =>
                {
                    b.HasOne("TgCheckerApi.Models.BaseModels.NotificationSetting", "NotificationSettingsNavigation")
                        .WithMany("Users")
                        .HasForeignKey("NotificationSettings")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("notification_settings_fk");

                    b.Navigation("NotificationSettingsNavigation");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.ViewsRecord", b =>
                {
                    b.HasOne("TgCheckerApi.Models.BaseModels.StatisticsSheet", "SheetNavigation")
                        .WithMany("ViewsRecords")
                        .HasForeignKey("Sheet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("StatisticsSheet_fk");

                    b.Navigation("SheetNavigation");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Channel", b =>
                {
                    b.Navigation("ChannelAccesses");

                    b.Navigation("ChannelHasSubscriptions");

                    b.Navigation("ChannelHasTags");

                    b.Navigation("Comments");

                    b.Navigation("NotificationsNavigation");

                    b.Navigation("Payments");

                    b.Navigation("Reports");

                    b.Navigation("StatisticsSheets");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Comment", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.NotificationSetting", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.ReportType", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Staff", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.StatisticsSheet", b =>
                {
                    b.Navigation("SubscribersRecords");

                    b.Navigation("ViewsRecords");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.SubType", b =>
                {
                    b.Navigation("ChannelHasSubscriptions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.Tag", b =>
                {
                    b.Navigation("ChannelHasTags");
                });

            modelBuilder.Entity("TgCheckerApi.Models.BaseModels.User", b =>
                {
                    b.Navigation("ChannelAccesses");

                    b.Navigation("Channels");

                    b.Navigation("Comments");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Reports");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
